make it safer

diff --git a/roles/base/files/users/sandro/bash/bash_functions b/roles/base/files/users/sandro/bash/bash_functions
--- a/roles/base/files/users/sandro/bash/bash_functions
+++ b/roles/base/files/users/sandro/bash/bash_functions
@@ -1,39 +1,38 @@
-## Functions
-# Make a directory, then go there
+# make a directory, then go there
 md() {
-    test -n "$1" || return
-    mkdir -p "$1" && cd "$1"
+    [ -n "$1" ] || return
+    mkdir -p "$1" && cd "$1" || return
 }
 
-# "path" shows current path, one element per line.
-# If an argument is supplied, grep for it.
+# show PATH, one element per line, optionally filtered
 path() {
-    test -n "$1" && {
-        echo $PATH | perl -p -e "s/:/\n/g;" | grep -i "$1"
-    } || {
-        echo $PATH | perl -p -e "s/:/\n/g;"
-    }
+    if [ -n "$1" ]; then
+        printf '%s\n' "$PATH" | tr ':' '\n' | grep -i -- "$1"
+    else
+        printf '%s\n' "$PATH" | tr ':' '\n'
+    fi
 }
 
-extract () {
-  if [ -f $1 ] ; then
-    case $1 in
-      *.tar.bz2)   tar xjvf $1    ;;
-      *.tar.gz)    tar xzvf $1    ;;
-      *.tar.xz)    tar xvf $1    ;;
-      *.bz2)       bzip2 -d $1    ;;
-      *.rar)       unrar2dir $1    ;;
-      *.gz)        gunzip $1    ;;
-      *.tar)       tar xf $1    ;;
-      *.tbz2)      tar xjf $1    ;;
-      *.tgz)       tar xzf $1    ;;
-      *.zip)       unzip2dir $1     ;;
-      *.Z)         uncompress $1    ;;
-      *.7z)        7z x $1    ;;
-      *.ace)       unace x $1    ;;
-      *)           echo "'$1' cannot be extracted via extract()"   ;;
+extract() {
+    [ -f "$1" ] || {
+        echo "'$1' is not a valid file"
+        return 1
+    }
+
+    case "$1" in
+        *.tar.bz2) tar xjvf "$1" ;;
+        *.tar.gz)  tar xzvf "$1" ;;
+        *.tar.xz)  tar xvf "$1" ;;
+        *.bz2)     bzip2 -d "$1" ;;
+        *.rar)     unrar2dir "$1" ;;
+        *.gz)      gunzip "$1" ;;
+        *.tar)     tar xf "$1" ;;
+        *.tbz2)    tar xjf "$1" ;;
+        *.tgz)     tar xzf "$1" ;;
+        *.zip)     unzip2dir "$1" ;;
+        *.Z)       uncompress "$1" ;;
+        *.7z)      7z x "$1" ;;
+        *.ace)     unace x "$1" ;;
+        *)         echo "'$1' cannot be extracted via extract()" ;;
     esac
-  else
-    echo "'$1' is not a valid file"
-  fi
 }
